# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mfrs_dfs_C <- function(node_count, link_array, composite_nodes, input_node, output_node, silent = TRUE) {
    .Call('_rmfr_mfrs_dfs_C', PACKAGE = 'rmfr', node_count, link_array, composite_nodes, input_node, output_node, silent)
}

mfrs_sgg_C <- function(node_count, invadj_list, node_composition, input_node, output_node, source_nodes, silent = TRUE) {
    .Call('_rmfr_mfrs_sgg_C', PACKAGE = 'rmfr', node_count, invadj_list, node_composition, input_node, output_node, source_nodes, silent)
}

