# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mfrs_dag <- function(node_count, link_array, composite_nodes, source_node, target_node) {
    .Call('_rmfr_mfrs_dag', PACKAGE = 'rmfr', node_count, link_array, composite_nodes, source_node, target_node)
}

